Repository meekrosoft/fff, pull requests merged in 2018-12, with the labels that each got.

#67 Added in-source appveyor config.
  .appveyor.yml
Labels: CI

#63 Custom return value delegate sequences for variadic functions
  README.md
  fakegen.rb
  fff.h
  test/fff_test_c.c
  test/fff_test_cpp.cpp
  test/fff_test_global_c.c
  test/fff_test_global_cpp.cpp
  test/test_cases.include
Labels: Feature, PR

#49 Remove extern "C" from fake declarations.
  examples/driver_testing/driver.test.fff.cpp
  fakegen.rb
  fff.h
  test/fff_test_cpp.cpp
Labels: Bug, PR
